### ISSUE TITLE
Kernel Panic

### ISSUE THREAD

**Issue by necrodst** [the-darkvoid/XPS9360-macOS#14] opened 2018-03-19 13:50 UTC
Hi and thanks for your work ;)

I succeded booting in Sierra Installion but can't see my NVMe SSD Toshiba 512GB in Disk utilities. I used https://pikeralpha.wordpress.com/2016/06/27/nvmefamily-kext-bin-patch-data/ to hotpatch my kext but it's not working 😢 

So I finally tried to boot up High Sierra installation but without success.
I used unibeast and then deployed clover on it, and I replaced EFI/CLOVER with yours.

I'm having a kernel panic but I can't see why. The stack trace is unreadable..

Here is a video of my boot sequence : https://cloud.myidea.fr/s/qqXgSwGaE6D5p6Z

Hope you could help me :/

Here is my laptop details : 
XPS 9360
i7-7560U
Iris pro 640 FHD
16GB RAM
HDD : Toshiba NVMe SSD 512GB

**Comment by the-darkvoid** [comment] 2018-03-23 12:48
@necrodst , assuming this is a duplicate of issue #4 . Try with the latest update.

**Closed by the-darkvoid** 2018-03-23 12:48 UTC

**Comment by necrodst** [comment] 2018-03-23 15:02
The fix worked, now internal sound is working but after 2/3 min of using the OS if freezing and I need to reboot.. After deleting injected kexts everything work well again :/
Also my mic wasn't working

**Comment by necrodst** [comment] 2018-03-23 15:24
Hi ! 

Everything is working fine !!!!
Thanks a lot !! 

I just have one more question. I'm using a dell dock wd15 and my 2 external monitors are recognized as the same screen (HDMI + TB or HDMI + VGA).
Have you got a solution for this ?

**Comment by the-darkvoid** [comment] 2018-03-24 14:02
The two monitors will always duplicate each other on macOS, this is because Apple does not support MST (Multiple Stream Transport).

https://discussions.apple.com/thread/7866674
